apiVersion: v1
kind: Service
metadata:
  name: javabenchmarkapp
spec:
  type: NodePort
  selector:
    app: javabenchmarkapp
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080