apiVersion: apps/v1
kind: Deployment
metadata:
  name: javabenchmarkapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javabenchmarkapp
  template:
    metadata:
      labels:
        app: javabenchmarkapp
    spec:
      containers:
      - name: javabenchmarkapp
        image: nclcloudcomputing/javabenchmarkapp
        ports:
        - containerPort: 8080